base/base/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dynabook/', include('dynabook.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('dynabook:index')))
]

base/dynabook/urls.py
from django.urls import path
from django.views import generic as gv
from django.contrib.auth import views as av

from dynabook import views as dv, forms as df

app_name = "dynabook"
urlpatterns = [
    path('', gv.TemplateView.as_view(template_name='base.html'), name='index'),
    path(
        'login/',
        av.LoginView.as_view(
            template_name='dynabook/login.html',
            extra_context={'no_nav': True},
            redirect_authenticated_user=True,
        ),
        name='login'
    ),
    path('logout/', av.LogoutView.as_view(), name='logout'),
    path(
        'register/',
        dv.RegisterView.as_view(
            extra_context={
                'form': df.RegistrationForm(),
                'no_nav': True,
                'title': 'Register',
            },
        ),
        name='register'
    ),
    path('popular/', dv.PopularUsersView.as_view(), name='popular_users'),
    path('search/', dv.SearchUserView.as_view(), name='search_user'),
    path('export/', dv.export_to_csv, name='export'),
    path(
        'password/change/',
        dv.PasswordUpdateView.as_view(),
        name='change_password'
    ),
    path('<slug:slug>/', dv.ProfileView.as_view(), name='profile'),
    path(
        '<slug:slug>/edit/',
        dv.ProfileEditView.as_view(),
        name='profile_edit'
    ),
    path(
        '<slug:slug>/edit/staff/',
        dv.ProfileEditStaffView.as_view(),
        name='profile_edit_staff'
    ),
    path(
        '<slug:slug>/manage/<str:direction>/',
        dv.ManageFriendsStaffView.as_view(),
        name='manage_friends'
    ),
    path(
        '<slug:slug>/change/<int:status>/',
        dv.change_status,
        name='change_status'
    ),
]

base/dynabook/forms.py
from django.contrib.auth import models as am, forms as af
from django.utils.text import slugify
from django import forms as f

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from dynabook import models as dm


class RegistrationForm(af.UserCreationForm):
    last_name = f.CharField(max_length=100)
    first_name = f.CharField(max_length=100)
    email = f.EmailField()

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.wrapper_class = 'row m-1'
        self.helper.field_class = 'col-md-9'
        self.helper.label_class = 'col-md-3'
        self.helper.form_class = 'p-0 pb-1 bg-light'
        self.helper.add_input(
            Submit(
                'submit', 'Submit',
                css_class='btn btn-primary'
            )
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save()
        dm.Person.objects.get_or_create(user=user, slug=slugify(user.username))
        return user

    class Meta:
        model = am.User
        fields = ('username', 'last_name', 'first_name', 'email')


class FriendFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(FriendFormSetHelper, self).__init__(*args, **kwargs)
        self.add_input(Submit('submit', 'Submit'))
        self.template = 'dynabook/table_inline_formset.html'


class FriendFormSet(f.BaseInlineFormSet):
    def clean(self):
        if any(self.errors):
            return
        persons = []
        for form in self.forms:
            data = form.cleaned_data.copy()
            if data:
                field_name = 'from_person' if \
                    form.__dict__['fields']['to_person'].widget.__class__.__name__ \
                    == 'HiddenInput' else 'to_person'
                person = data[field_name]
                if person in persons:
                    form.add_error(field_name, "Persons must be distinct")
                if data['from_person'] == data['to_person']:
                    form.add_error(field_name, "Cannot be the same person")
                persons.append(person)

base/dynabook/views.py
import csv
import datetime

from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView, CreateView, DetailView, ListView, UpdateView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth import models as am
from django.db.models import Q
from django.utils.text import slugify
from django.utils import timezone
from django.forms import inlineformset_factory

from dynabook import forms as df, models as dm


def filter_user(request, person=None):
    result = dm.Person.objects.all()
    if person and not request.user.is_staff:
        blocked = person.get_blocked()
        result = result.exclude(pk__in=blocked)
    name_query = request.GET.get('q')
    if name_query:
        result = result.filter(
            Q(user__last_name__icontains=name_query) |
            Q(user__first_name__icontains=name_query)
        )
    date_query = request.GET.get('o')
    if date_query:
        date_query = date_query.lower()
        date_query_selection = ['yesterday', 'lastweek', 'lastmonth']
        if date_query in date_query_selection:
            if date_query == 'lastmonth':
                value = datetime.timedelta(days=30)
            elif date_query == 'lastweek':
                value = datetime.timedelta(days=7)
            else:
                value = datetime.timedelta(days=1)
            time = timezone.now() - value
            result = result.filter(user__date_joined__gte=time)
    result.order_by(
        'user__last_name',
        'user__first_name',
        '-user__date_joined'
    )
    sort = request.GET.get('s')
    if sort and sort in [
        'name', '-name',
        'date_joined', '-date_joined',
        'count', '-count',
        'dcount', '-dcount',
    ]:
        if sort == 'name':
            result = sorted(
                result,
                key=lambda r: (r.user.last_name, r.user.first_name)
            )
        elif sort == '-name':
            result = sorted(
                result,
                key=lambda r: (r.user.last_name, r.user.first_name),
                reverse=True
            )
        elif sort == 'date_joined':
            result = sorted(
                result,
                key=lambda r: r.user.date_joined
            )
        elif sort == '-date_joined':
            result = sorted(
                result,
                key=lambda r: r.user.date_joined,
                reverse=True
            )
        elif sort == 'count':
            result = sorted(
                result,
                key=lambda r: r.get_friends_count()
            )
        elif sort == '-count':
            result = sorted(
                result,
                key=lambda r: r.get_friends_count(),
                reverse=True
            )
        elif sort == 'dcount':
            result = sorted(
                result,
                key=lambda r: r.get_defriended_count(),
            )
        elif sort == '-dcount':
            result = sorted(
                result,
                key=lambda r: r.get_defriended_count(),
                reverse=True
            )
    return result


# Create your views here.
class SearchUserView(ListView):
    paginate_by = 10
    context_object_name = 'search_results'
    template_name = 'dynabook/search_user.html'

    def get_queryset(self):
        try:
            return filter_user(self.request, self.request.user.person)
        except AttributeError:
            return filter_user(self.request)


class RegisterView(CreateView):
    form_class = df.RegistrationForm
    success_url = reverse_lazy('dynabook:login')
    template_name = 'dynabook/register.html'


class ProfileView(DetailView):
    model = dm.Person
    template_name = 'dynabook/profile_view.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        person = dm.Person.objects.get(slug=self.kwargs['slug'])
        context['status'] = dm.status
        context['friends'] = person.get_friends()
        if self.request.user.is_authenticated:
            try:
                user = self.request.user.person
            except dm.Person.DoesNotExist:
                user = None
            # Determine buttons to show
            if user:
                if user == person:
                    context['status_self'] = True
                else:
                    relation_status = user.get_status(person)
                    relation_type = user.get_connect_type(person)
                    if relation_status == dm.status['P']['value']:
                        if relation_type == 'source':
                            context['status_cancel_request'] = True
                        else:
                            context['status_accept_or_reject_request'] = True
                    elif relation_status == dm.status['A']['value']:
                        context['status_friend'] = True
                    elif relation_status == dm.status['B']['value']:
                        if relation_type == 'source':
                            context['status_block_source'] = True
                        else:
                            context['status_block_target'] = True
        return context


class ProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = am.User
    template_name = 'dynabook/profile_edit.html'
    fields = ('username', 'last_name', 'first_name', 'email')
    success_message = 'Profile Edited!'

    def get_object(self, queryset=None):
        return am.User.objects.get(person__slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse_lazy('dynabook:profile', args=(self.kwargs['slug'],))

    def form_valid(self, form):
        person = dm.Person.objects.get(slug=self.kwargs['slug'])
        slug = slugify(form.cleaned_data['username'])
        person.slug = slug
        self.kwargs['slug'] = slug
        person.save()
        return super().form_valid(form)


class StaffTestMixin(UserPassesTestMixin):
    def test_func(self):
        return staff_test(self.request.user)


class ProfileEditStaffView(StaffTestMixin, ProfileEditView):
    fields = (
        'username', 'last_name', 'first_name', 'email',
        'is_active', 'is_staff', 'is_superuser',
    )
    login_url = reverse_lazy('dynabook:login')


class PasswordUpdateView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'dynabook/password_change.html'
    success_url = reverse_lazy('dynabook:home')
    success_message = 'Password Changed!'


@login_required
def change_status(request, slug, status):
    person = dm.Person.objects.get(slug=slug)
    try:
        user = dm.Person.objects.get(user=request.user)
    except dm.Person.DoesNotExist:
        user = None
    if user and request.user.person.change_status(person, status):
        key = dm.get_status_key(status)
        messages.add_message(
            request,
            dm.status[key]['tag'],
            dm.status[key]['message']
        )
    else:
        messages.add_message(request, messages.ERROR, 'Action not allowed!')
    return redirect(reverse('dynabook:profile', args=(slug,)))


def staff_test(user):
    if user.is_staff:
        return True
    raise Http404()


@login_required
@user_passes_test(staff_test)
def export_to_csv(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="user_data.csv"'
    # Create the csv file
    writer = csv.writer(response)
    head = ['Name', 'Date Joined', 'Friend Count']
    if request.user.is_staff:
        head.append('Defriend Count')
    writer.writerow(head)
    # Get rows to write
    result = filter_user(request)
    # Write rows to file
    for person in result:
        row = [
            person.user.get_full_name(),
            person.user.date_joined,
            person.get_friends_count()
        ]
        if request.user.is_staff:
            row.append(person.get_defriended_count())
        writer.writerow(row)
    return response


def create_friends_formsets(person, direction='from', post=None):
    if direction == 'to':
        query = dm.Friend.objects.filter(from_person=person, active=1)
        fk_field, form_field = 'from_person', 'to_person'
    else:
        query = dm.Friend.objects.filter(to_person=person, active=1)
        fk_field, form_field = 'to_person', 'from_person'
    PersonInlineFormSet = inlineformset_factory(
        dm.Person, dm.Friend,
        fk_name=fk_field,
        fields=(form_field, 'status'),
        formset=df.FriendFormSet,
        extra=5)
    PersonFormset = PersonInlineFormSet(post, instance=person, queryset=query)
    return PersonFormset


class ManageFriendsStaffView(LoginRequiredMixin, StaffTestMixin, TemplateView):
    def get(self, request, *args, **kwargs):
        direction = kwargs['direction']
        if direction.lower() not in ('to', 'from'):
            raise Http404()
        slug = kwargs['slug']
        person = dm.Person.objects.get(slug=slug)
        helper = df.FriendFormSetHelper()
        personFormSet = create_friends_formsets(person, direction)
        return render(
            request,
            'dynabook/manage_friends_staff.html',
            {
                'formset': personFormSet,
                'helper': helper,
                'direction': direction,
            }
        )

    def post(self, request, *args, **kwargs):
        slug = kwargs['slug']
        person = dm.Person.objects.get(slug=slug)
        helper = df.FriendFormSetHelper()

base/dynabook/templates/dynabook/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="d-md-flex align-items-center flex-column justify-content-center h-100">
    <div>
        <h2 class='bg-success p-2 rounded-top text-light mb-0'>Login</h2>
        <form method="POST" class="bg-light p-2">
            <fieldset>
                {% csrf_token %}
                {{ form|crispy }}
                <button class='btn btn-warning'>Submit</button>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

base/dynabook/templates/dynabook/manage_friends_staff.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Manage Friends {{ direction }} {{ slug }} {% endblock %}

{% block content %}
<div class="container my-2">
    <h4>Connection {{ direction }} other persons</h4>
    {% crispy formset helper %}
</div>
{% endblock %}

base/dynabook/templates/dynabook/password_change.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Change Password{% endblock %}

{% block content %}
<div class="d-md-flex align-items-center flex-column justify-content-center h-100">
    <div>
        <h2 class='bg-success p-2 rounded-top text-light mb-0'>Change Password</h2>
        <form method="POST" class="bg-light p-2">
            {% csrf_token %}
            {{ form|crispy }}
            <button class='btn btn-primary'>Submit</button>
        </form>
    </div>
</div>
{% endblock %}

base/dynabook/templates/dynabook/popular_users.html
{% extends 'base.html' %}

{% block title %}Search User{% endblock %}
{% block content %}
{% with param=request.GET %}
    <div class="container my-2">
        <div class="row">
            <div class="col-8">
                <h4 class='mt-2'>
                    Popular Users 
                </h4>
                <ol>
                    {% for result in popular_users_results %}
                        <li><a href="{% url 'dynabook:profile' result.user.person.slug %}">{{ result.user.get_full_name }}</a></li>
                    {% empty %}
                        <li>No results</li>
                    {% endfor %}
                </ol>
            </div>
            <div class="col-4">
                <h4 class='bg-secondary rounded-top px-2 py-1 mb-0 row mx-auto'>
                    <span class="col-md-9">Period</span>
                    <small class="col-md-3"><a href="?">(Clear)</a></small>
                </h4>
                <div class="bg-light border border-bottom border-secondary">
                    <ul>
                        <li><a href="?f=daily">Daily</a></li>
                        <li><a href="?f=weekly">Weekly</a></li>
                        <li><a href="?f=monthly">Monthly</a></li>
                        <li><a href="?f=yearly">Yearly</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endwith %}
{% endblock %}

base/dynabook/templates/dynabook/profile_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Edit - {{ user.person.slug }}{% endblock %}

{% block content %}
<div class="row my-3">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h3 class='bg-success p-2 rounded-top text-light mb-0 w-100'>Edit Profile</h3>
        <form method='POST' class='p-2 bg-light'>
            {% csrf_token %}
            {{ form|crispy }}
            <button class='btn btn-primary'>Submit</button>
        </form>
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}

base/dynabook/templates/dynabook/profile_view.html
{% extends 'base.html' %}

{% block title %}Profile - {{ person.slug }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Profile</h2>
            <div class="row">
                <div class="col-3">Name</div>
                <div class="col-9">{{ person.user.get_full_name }}</div>
            </div>
            <div class="row">
                <div class="col-3">Email Address</div>
                <div class="col-9">{{ person.user.email }}</div>
            </div>
            <div class="row">
                <div class="col-3">Actions</div>
                <div class="col-9">
                {% if user.is_authenticated %}
                    {% if status_self %}
                        <a href="{% url 'dynabook:profile_edit' person.slug %}" class='btn btn-warning'>Edit Profile</a>
                    {% endif %}
                    {% if not status_self and user.person %}
                        {% if status_accept_or_reject_request %}
                            <a href="{% url 'dynabook:change_status' person.slug status.A.value %}" class='btn btn-primary'>Accept Friend Request</a>
                            <a href="{% url 'dynabook:change_status' person.slug status.R.value %}" class='btn btn-warning'>Reject Friend Request</a>
                        {% elif status_cancel_request %}
                            <a href="{% url 'dynabook:change_status' person.slug status.C.value %}" class='btn btn-warning'>Cancel Friend Request</a>
                        {% elif status_friend %}
                            <a href="{% url 'dynabook:change_status' person.slug status.D.value %}" class='btn btn-danger'>Defriend</a>
                        {% elif status_block_source %}
                            <a href="{% url 'dynabook:change_status' person.slug status.U.value %}" class='btn btn-warning'>Unblock Person</a>
                        {% else %}
                            {% if not status_block_target %}
                                <a href="{% url 'dynabook:change_status' person.slug status.P.value %}" class='btn btn-primary'>Add Friend</a>
                            {% endif %}
                        {% endif %}
                        {% if not status_block_source %}
                            <a href="{% url 'dynabook:change_status' person.slug status.B.value %}" class='btn btn-danger'>Block Person</a>
                        {% endif %}
                    {% endif %}
                    {% if user.is_staff %}
                        <a href="{% url 'dynabook:profile_edit_staff' person.slug %}" class='btn btn-warning'>Edit Profile (Staff)</a>
                        <a href="{% url 'dynabook:manage_friends' person.slug 'to' %}" class='btn btn-warning'>Manage Connection TO Others (Staff)</a>
                        <a href="{% url 'dynabook:manage_friends' person.slug 'from' %}" class='btn btn-warning'>Manage Connection FROM Others (Staff)</a>
                    {% endif %}
                {% else  %}
                    <a class="btn btn-primary" href="{% url 'dynabook:login' %}?next={{ request.path }}">Login to Connect</a>
                {% endif %}
                </div>
            </div>
            {% if status_friend or status_self or user.is_staff  %}
                <h3>Friends</h3>
                <ul>
                {% for friend in friends %}
                    <li>
                        <a href="{% url 'dynabook:profile' friend.slug %}">
                            {{ friend.name }}
                            {% if friend.slug == request.user.person.slug %}
                                (ME)
                            {% endif %}
                        </a>
                    </li>
                {% empty %}
                    <li> No Friends Yet </li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

base/dynabook/templates/dynabook/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="d-md-flex align-items-center flex-column justify-content-center h-100">
    <div>
        <h3 class='bg-success p-2 rounded-top text-light mb-0 w-100'>Register</h3>
        {% crispy form %}
    </div>
</div>
{% endblock %}

base/dynabook/templates/dynabook/search_user.html
{% extends 'base.html' %}

{% block title %}Search User{% endblock %}
{% block content %}
{% with param=request.GET %}
    <div class="container my-2">
        <div class="row">
            <div class="col-8">
                <form method='GET'>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Search Users</span>
                        </div>
                        <input type="text" name="q" class="form-control" aria-label="Search" value="{{ param.q }}" autofocus>
                        {% if param.o %}
                            <input type="hidden" name="o" value="{{ param.o }}">
                        {% endif %}
                        {% if param.s %}
                            <input type="hidden" name="s" value="{{ param.s }}">
                        {% endif %}
                        <div class="input-group-append">
                            <button class="btn btn-success">Go</button>
                        </div>
                    </div>
                </form>
                <h4 class='mt-2'>
                    Results
                    {% if user.is_staff %}
                        <a href="{% url 'dynabook:export' %}?q={{ param.q }}&o={{ param.o }}&s={{ param.s }}" class='btn btn-warning'>Export</a>
                    {% endif %}
                </h4>
                <table class="table table-striped table-hover my-2">
                    <thead class="bg-secondary">
                        <tr>
                            <td><a href="?{% if param.q %}q={{ param.q }}{% endif %}{% if param.o %}{% if param.q %}&{% endif %}o={{ param.o }}{% endif %}{% if not param.s or param.s != 'name' and param.s != '-name' %}{% if param.q or param.o %}&{% endif %}s=name{% elif param.s == 'name' %}{% if param.q or param.o %}&{% endif %}s=-name{% endif %}{% if param.page %}&page={{ param.page }}{% endif %}">Name</a></td>
                            <td><a href="?{% if param.q %}q={{ param.q }}{% endif %}{% if param.o %}{% if param.q %}&{% endif %}o={{ param.o }}{% endif %}{% if not param.s or param.s != 'date_joined' and param.s != '-date_joined' %}{% if param.q or param.o %}&{% endif %}s=date_joined{% elif param.s == 'date_joined' %}{% if param.q or param.o %}&{% endif %}s=-date_joined{% endif %}{% if param.page %}&page={{ param.page }}{% endif %}">Date Joined</a></td>
                            <td><a href="?{% if param.q %}q={{ param.q }}{% endif %}{% if param.o %}{% if param.q %}&{% endif %}o={{ param.o }}{% endif %}{% if not param.s or param.s != 'count' and param.s != '-count' %}{% if param.q or param.o %}&{% endif %}s=count{% elif param.s == 'count' %}{% if param.q or param.o %}&{% endif %}s=-count{% endif %}{% if param.page %}&page={{ param.page }}{% endif %}">Friend Count</a></td>
                            {% if user.is_staff %}
                                <td><a href="?{% if param.q %}q={{ param.q }}{% endif %}{% if param.o %}{% if param.q %}&{% endif %}o={{ param.o }}{% endif %}{% if not param.s or param.s != 'dcount' and param.s != '-dcount' %}{% if param.q or param.o %}&{% endif %}s=dcount{% elif param.s == 'dcount' %}{% if param.q or param.o %}&{% endif %}s=-dcount{% endif %}{% if param.page %}&page={{ param.page }}{% endif %}">Defriend Count</a>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                    {% for result in search_results %}
                        <tr>
                            <td><a href="{% url 'dynabook:profile' result.user.person.slug %}">{{ result.user.get_full_name }}</a></td>
                            <td>{{ result.user.date_joined }}</td>
                            <td>{{ result.user.person.get_friends_count }}</td>
                            {% if user.is_staff %}
                                <td>{{ result.user.person.get_defriended_count }}</td>
                            {% endif %}
                        </tr>
                    {% empty %}
                        <tr class='table-danger'>
                            <td colspan="3" class='text-center'>No users' match the query</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}{% if param.q %}&q={{ param.q }}{% endif %}{% if param.o %}&o={{ param.o }}{% endif %}{% if param.s %}&s={{ param.s }}{% endif %}">Previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}{% if param.q %}&q={{ param.q }}{% endif %}{% if param.o %}&o={{ param.o }}{% endif %}{% if param.s %}&s={{ param.s }}{% endif %}">Next</a>
                        {% endif %}
                    </span>
                </div>
                {% endif %}
            </div>
            <div class="col-4">
                <h4 class='bg-secondary rounded-top px-2 py-1 mb-0'>Filter</h4>
                <div class="bg-light border border-bottom border-secondary">
                    <h5 class="row mx-auto">
                        <span class="col-md-9">Date Joined</span>
                        <small class="col-md-3">
                            <a href="?{% if param.q %}q={{ param.q }}{% endif %}{% if param.s %}{% if param.q %}&{% endif %}s={{ param.s }}{% endif %}">(Clear)</a>
                        </small>
                    </h5>
                    <ul>
                        <li><a href="?{% if param.q %}q={{ param.q }}&{% endif %}o=yesterday{% if param.s %}&s={{ param.s }}{% endif %}">Yesterday</a></li>
                        <li><a href="?{% if param.q %}q={{ param.q }}&{% endif %}o=lastweek{% if param.s %}&s={{ param.s }}{% endif %}">Last Week</a></li>
                        <li><a href="?{% if param.q %}q={{ param.q }}&{% endif %}o=lastmonth{% if param.s %}&s={{ param.s }}{% endif %}">Last Month</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endwith %}
{% endblock %}

base/dynabook/templates/dynabook/table_inline_formset.html
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load crispy_forms_field %}

{% specialspaceless %}
{% if formset_tag %}
<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if formset.is_multipart %} enctype="multipart/form-data"{% endif %}>
{% endif %}
    {% if formset_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    <div>
        {{ formset.management_form|crispy }}
    </div>

    <table{% if form_id %} id="{{ form_id }}_table"{% endif%} class="table table-striped table-condensed">
        <thead>
            {% if formset.readonly and not formset.queryset.exists %}
            {% else %}
                <tr>
                    {% for field in formset.forms.0 %}
                        {% if field.label and not field.is_hidden %}
                            <th for="{{ field.auto_id }}" class="control-label {% if field.field.required and not field|is_checkbox %}requiredField{% endif %}">
                                {{ field.label|safe }}{% if field.field.required and not field|is_checkbox %}<span class="asteriskField">*</span>{% endif %}
                            </th>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endif %}
        </thead>

        <tbody>
            <tr class="d-none empty-form">
                {% for field in formset.empty_form %}
                    {% include 'bootstrap4/field.html' with tag="td" form_show_labels=False %}
                {% endfor %}
            </tr>

            {% for form in formset %}
                {% if form_show_errors and not form.is_extra %}
                    {% include "bootstrap4/errors.html" %}
                {% endif %}

                <tr>
                    {% for field in form %}
                        {% include 'bootstrap4/field.html' with tag="td" form_show_labels=False %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if inputs %}
        <div class="form-actions">
            {% for input in inputs %}
                {% include "bootstrap4/layout/baseinput.html" %}
            {% endfor %}
        </div>
    {% endif %}
{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}